services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - cleverleafy-net

networks:
  cleverleafy-net:
    name: cleverleafy
    external: true